config/routes.rb
Rails.application.routes.draw do
  
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password, controller: "clearance/passwords", only: [:create, :edit, :update]
    resources :reservations, only: :index
  end

  resources :users, only: [:new, :show, :edit, :update, :destroy]

  resources :listings do
    resources :reservations, except: :index
  end

  resources :users do 
    resources :reservations
  end
  
  resources :transactions

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'home#index'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
 

end

app/models/autentication.rb
class Authentication < ActiveRecord::Base

     belongs_to :user

      def self.create_with_omniauth(auth_hash)
        create! do |auth|
          auth.provider = auth_hash["provider"]
          auth.uid = auth_hash["uid"]
          auth.token = auth_hash["credentials"]["token"]
        end
      end

      def update_token(auth_hash)
        self.token = auth_hash["credentials"]["token"]
        self.save
      end

    end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user

    def self.create_with_omniauth(auth_hash)
      create! do |auth|
        auth.provider = auth_hash["provider"]
        auth.uid = auth_hash["uid"]
        auth.token = auth_hash["credentials"]["token"]
      end
    end

    def update_token(auth_hash)
      self.token = auth_hash["credentials"]["token"]
      self.save
    end

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :reservations, :dependent => :destroy
	searchkick
	mount_uploader :image, ImageUploader
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :reservation
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :authentications, :dependent => :destroy
	has_many :listings, :dependent => :destroy
	has_many :reservations, :dependent => :destroy
  include Clearance::User

  mount_uploader :avatar, AvatarUploader
 
  def self.create_with_auth_and_hash(authentication,auth_hash)
    create! do |u|
      u.first_name = auth_hash["info"]["first_name"]
      u.email = auth_hash["extra"]["raw_info"]["email"]
      u.password = SecureRandom.hex(4)
      u.authentications<<(authentication)
    end
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  #include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@listings = Listing.all
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index
		Listing.reindex
		@listings = Listing.search(params[:search])
	end

	def new
		@listing = Listing.new
	end

	def create
		@user = current_user
		@listing = @user.listings.new(listing_params)
		if @listing.save
			redirect_to listing_path(current_user.id)
		else 
			redirect_to new_listing_path, alert: "Error creating listing."
		end
    end

    def show
    	@listing = Listing.find(params[:id])
    	@reservation = @listing.reservations.new
	end

	def listing_params
    	params.require(:listing).permit(:title, :city, :hometype, :roomtype, :accommodates, :available_from, :available_until, :price, :currency, :user_id, :image)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
		@reservation = Reservation.new
		@reservations = Reservation.all
	end

	def new
		@reservation = Reservation.new
	end

	def create
		@reservation = current_user.reservations.new(reservation_params)
		@user = @reservation.user
		if @reservation.save
		ReservationMailer.reservation_email(@user).deliver_now
		redirect_to new_transaction_path
		else 
		redirect_to root_path
		end
    end

    def reservation_params
    	params.require(:reservation).permit(:city, :check_in, :check_out, :guests, :user_id, :listing_id)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController

      def create_from_omniauth
        auth_hash = request.env["omniauth.auth"]

        authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
        if authentication.user
          user = authentication.user 
          authentication.update_token(auth_hash)
          @next = user_path(user)
          @notice = "Signed in!"
        else
          user = User.create_with_auth_and_hash(authentication,auth_hash)
          @next = edit_user_path(user)   
          @notice = "User created - confirm or edit details..."
        end
        sign_in(user)
        redirect_to @next, :notice => @notice
      end
    end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

	def new
 	gon.client_token = generate_client_token
 	@reservation = Reservation.where(user_id: current_user.id).last
 	@listing = Listing.find(@reservation.listing_id)
 	length_of_stay = @reservation.check_out - @reservation.check_in
  @total_price = @listing.price.to_s.to_f.round(2) * length_of_stay
	end

	def create
		#result will give you a set of params, transaction id provided by paypal would be worth keeping in the db
    @result = Braintree::Transaction.sale(amount: params[:price], payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
    	Transaction.create(reservation_id: params[:reservation])
      redirect_to user_reservations_path(current_user.id), notice: "Transaction processed!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end

	private
	def generate_client_token
  	Braintree::ClientToken.generate
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
    	@user = User.find(params[:id])
  	end

  	def new
    	@user = User.new
  	end

  	def create
  		@user = User.new
  		if @user.save
  			redirect_to edit_user_path(current_user.id)
  		else 
  			redirect_to user_path(current_user.id)
  		end
  	end 

  	def edit
    	@user = User.find(params[:id])
  	end

  	def update
  		@user = User.find(params[:id])
  		if @user.update(user_params)
    		redirect_to user_path(current_user.id)
    	else
      		render 'edit'
    	end
  	end

  private

	def user_params
	    params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password, :confirmation_token, :remember_token, :avatar)
	end
end

   

app/helpers/application_helper.rb
module ApplicationHelper

	# def current_user
	# 	#if user.id == session[:user_id]
	# 		@current_user ||= User.find(session[:user_id]) if session[:user_id]
			
	# 	#end
	# 	# @current_user
	# end

	def logged_in?
		!current_user.nil?
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="container">
<div id="carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
    <li data-target="#carousel" data-slide-to="2"></li>
  </ol>
 
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag 'background.jpg' %>
      <div class="carousel-caption">
        <h3>Caption Text</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'bike.jpg' %>
      <div class="carousel-caption" %>
        <h3>Caption Text</h3>
      </div>
    </div>
    <div class="item">
      <%= image_tag 'sugarloaf.jpg' %>
      <div class="carousel-caption">
        <h3>Caption Text</h3>
      </div>
    </div>
  </div>
 
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->
</div>

app/views/layouts/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
 <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
   <a class="navbar-brand" href= <%= root_url %>>pairBnB</a>
   </div>
   <div id="navbar" class="navbar-collapse collapse">
   <ul class="nav navbar-nav">
   <li><%= link_to "Login", sign_in_path %></li>
   <li><%= link_to "Signup", sign_up_path %></li>
   <li><%= link_to "About Us", "#" %></li>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pairbnb</title>

  <!-- Latest compiled and minified CSS -->
<%= include_gon %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'vendor/modernizr', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<link href='https://fonts.googleapis.com/css?family=Cuprum' rel='stylesheet' type='text/css'>

</head>
<body class="background">

<div class="container">
	<ul class="nav nav-tabs">
	<% if signed_in? %>
		<div class="nav navbar-nav navbar-left">
		<li><%= link_to "Home", root_path %></li>
		<% unless current_user.first_name.nil? %>
		<li><%= link_to "My profile", user_path(current_user.id) %></li>
		<% else %>
		<li><%= link_to "Edit profile", edit_user_path(current_user.id) %></li><% end %>
		<li><%= link_to "My reservations", user_reservations_path(current_user.id) %></li>
		<li><%= link_to "Become a host", new_listing_path %></li></div>
		<div class="nav navbar-nav navbar-right">
		<li><%= image_tag current_user.avatar.url(:thumb).to_s, :class => "circle" %></li>
		<li><%= link_to "#{current_user.first_name}", user_path(current_user.id) %></li>
		<li><%= link_to "Sign out", sign_out_path, method: :delete %></li></div>
	<% else %>
		<li><%= link_to "Log in", sign_in_path %></li>
		<li><%= link_to "Sign up", sign_up_path %></li>
	<% end %>
	 </ul>
</div>

<div class="jumbotron">
	<div class="container">
    	<h1>Welcome to myBnB!</h1>
   	 	<p>Under construction...</p>
   	 </div>
</div>

<div class="container">
	<div class="center" "search">
	<% if signed_in? %>
	<%= form_tag(listings_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Where do you want to go?", :class => "searchbar" %>
	<%= submit_tag "Search", :name => nil %><% end %><% end %>
</div>
</div>
<br>
<%= yield %>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>

<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

</html>

app/views/listings/_form.html.erb
<%= form_for @listing do |f| %>

	<%= f.label :title %> <%= f.text_field :title %><br/>
	<%= f.label :city %> <%= f.text_field :city %><br/>
	<%= f.label :hometype, "Home type" %> <%= f.text_field :hometype %><br/>
	<%= f.label :roomtype, "Room type" %> <%= f.text_field :roomtype %><br/>
	<%= f.label :accommodates %> <%= f.number_field :accommodates %><br/>
	<%= f.label :available_from %> <%= f.date_field :available_from %><br/>
	<%= f.label :available_until %> <%= f.date_field :available_until %><br/>
	<%= f.label :price %> <%= f.number_field :price %><br/>
	<%= f.label :currency %> <%= f.text_field :currency %><br/>
	<%= f.label :image %> <%= f.file_field :image %><br/>

	<%= f.submit %>
 
<% end %>

app/views/listings/index.html.erb
<div class="container">
	<h1 class="border-bottom">Listings matching your criteria</h1>

	<% @listings.each do |listing| %>
		<ul><h3><%= listing.title %></h3></ul>
		<ul><% if listing.image.present? %>
		<%= image_tag listing.image.url.to_s %>
		<% else %>
		<%= image_tag 'no_image.jpg', :class => "no_image" %><br>
		<% end %></ul>
		<ul><%= link_to "Book this!", listing, :class => "btn btn-primary" %></ul>
	<% end %>
</div>

app/views/listings/new.html.erb
<div class="container">
	<h1>List your space</h1>
	<%= render 'form' %>
</div>

app/views/listings/show.html.erb
<div class="container">
	<h2><%= @listing.title %></h2><br> 
	<%= image_tag @listing.image.url.to_s %><br>
		
	Accommodates: <%= @listing.accommodates %> people<br>
	Available from <%= @listing.available_from %> until <%= @listing.available_until %><br>
	Price: <%= @listing.price %> <%= @listing.currency %> per night<br>
	Listed by <%= link_to "#{@listing.user.first_name}", user_path(@listing.user_id) %><br><br>

	<%= render partial: '/reservations/form' %>

	<%= link_to "Back", listings_path %>

</div>

app/views/reservations/_form.html.erb
<%= form_for [@listing, @reservation], url: listing_reservations_path(@listing) do |f| %>

	<%= f.label :check_in %> <%= f.date_field :check_in %><br>	
	<%= f.label :check_out %> <%= f.date_field :check_out %><br>
	<%= f.hidden_field :listing_id, value: @listing.id %>


	<%= f.submit %>
 
<% end %>

app/views/reservations/index.html.erb
<div class="container">
<div class="form-align">
<h1>My reservations</h1>

<% current_user.reservations.each do |reservation| %>
	<%= reservation.listing.title %> in <%= reservation.listing.city %><br>
	Listed by: <%= link_to "#{reservation.listing.user.first_name}", user_path(reservation.listing.user_id) %> <br><br>
	<% end %>
</div>
</div>

app/views/transactions/_form.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
  <%= form_tag transactions_path do%>
    <p>Please enter your payment details:</p>
    <div class="searchbar">
    <div id="dropin"></div>
    <%=submit_tag "Pay #{@total_price}", class: "button mt1" %>
    <%=hidden_field_tag "price", @total_price %>
    <%=hidden_field_tag "reservation", @reservation.id %>
  <%end%>
</div>
</div>

app/views/transactions/new.html.erb
<div class="container">
	<%= render partial: '/transactions/form' %>
</div>

app/views/users/_form.html.erb
<% unless signed_in? %> 
<form class="form-horizontal">
  <div class="searchbar">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
    <%= form.email_field :email, type: 'email', class: 'form-control', id: 'inputEmail3', placeholder:'Email' %>
    </div>
  </div>
  <div class="searchbar">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
    <%= form.password_field :password, type: 'password', class: 'form-control', id: 'inputPassword3', placeholder: 'password'%>
    </div>
  </div>
  <div class="searchbar">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="searchbar">
    <div class="col-sm-offset-2">
    <%= form.submit 'Sign up', class: "btn btn-danger" %><br>
    <%= link_to "Already a user?", sign_in_path %>
    </div>
  </div>
</form>

<% else %>
<%= form_for @user, method: :patch  do |f| %>

  <%= f.label :first_name %> <%= f.text_field :first_name %><br/>
  <%= f.label :last_name %> <%= f.text_field :last_name %><br/>
  <%= f.label :avatar %> <%= f.file_field :avatar %><br/> 

<%= f.submit %>
<% end %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
	<h1>Edit your profile</h1>
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<h1>Welcome, <%= current_user %></h1>

app/views/users/new.html.erb
<div class="container">
	<div id="clearance">
		<h2><%= t(".title") %></h2>	
		<%= form_for @user do |form| %>
		<%= render partial: '/users/form', object: form %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">	
	<div class="row">
	  	<div class="col-md-2">
	  		<%= image_tag @user.avatar.url.to_s, :class => "round" %>
	  	</div>
		<div class="col-md-6">
			<h1><%= @user.first_name %> <%= @user.last_name %></h1>
			<% if @user.id = current_user.id %>
				<%= link_to "Edit profile", edit_user_path(current_user.id), class: "btn btn-warning" %>
			<% end %>
		</div>
		<div class="col-md-4">
		<h2>My listings</h2>
		<% current_user.listings.each do |listing| %>
		<%= link_to "#{listing.title}", listing %><br>
		<% end %>
		<h2>My reservations</h2>
		<% current_user.reservations.each do |reservation| %>
		<%= reservation.listing.title %><br>
		<% end %>
		</div>
	</div>
</div>